In [1]:
from so100_robot_control.robot_interface import RobotInterface
import torch
import time
import numpy as np

pybullet build time: Mar 29 2025 10:54:55


In [2]:
robot = RobotInterface()
home = torch.tensor([ 0.0039,  90.0, 90.0,  90,  90,   0.0000])
print(robot.get_observation())
robot.send_action(home)
print(robot.get_observation())

INFO:so100_robot_control.robot_interface:SDK initialized.
INFO:so100_robot_control.robot_interface:Joint angles: tensor([-8.7891e-02,  8.4639e+01,  9.3604e+01,  8.9561e+01,  8.9824e+01,
         6.8788e-01])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00028122 -0.15852628  0.08094659]
INFO:so100_robot_control.robot_interface:Stopping the robot.
INFO:so100_robot_control.robot_interface:Robot disconnected.
INFO:so100_robot_control.robot_interface:Joint angles: tensor([-8.7891e-02,  8.4463e+01,  9.3604e+01,  8.9561e+01,  8.9824e+01,
         6.8788e-01])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00028104 -0.15840881  0.08047821]


Joint: Joint(name='Wrist_Roll', type='continuous', parent='Wrist_Pitch_Roll', child='Fixed_Jaw', origin=array([[ 1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  1.    ,  0.    , -0.0601],
       [ 0.    ,  0.    ,  1.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]]), axis=array([0., 1., 0.]), dynamics=None, limit=None, mimic=None, calibration=None, safety_controller=None)
Joint: Joint(name='Wrist_Pitch', type='continuous', parent='Lower_Arm', child='Wrist_Pitch_Roll', origin=array([[1.    , 0.    , 0.    , 0.    ],
       [0.    , 1.    , 0.    , 0.0052],
       [0.    , 0.    , 1.    , 0.1349],
       [0.    , 0.    , 0.    , 1.    ]]), axis=array([1., 0., 0.]), dynamics=None, limit=None, mimic=None, calibration=None, safety_controller=None)
Joint: Joint(name='Elbow', type='continuous', parent='Upper_Arm', child='Lower_Arm', origin=array([[1.     , 0.     , 0.     , 0.     ],
       [0.     , 1.     , 0.     , 0.11257],
       [0.     , 0.     , 1.     , 0.028  ],
  

INFO:so100_robot_control.robot_interface:Joint angles: tensor([-8.7891e-02,  8.4287e+01,  9.3779e+01,  8.9561e+01,  8.9824e+01,
         6.8788e-01])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00028016 -0.15783467  0.07966292]
INFO:so100_robot_control.robot_interface:Joint angles: tensor([-8.7891e-02,  8.3936e+01,  9.3867e+01,  8.9561e+01,  8.9824e+01,
         6.8788e-01])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00027943 -0.15736136  0.07855908]


(tensor([-8.7891e-02,  8.4287e+01,  9.3779e+01,  8.9561e+01,  8.9824e+01,
         6.8788e-01]), array([ 0.00028016, -0.15783467,  0.07966292]))
(tensor([-8.7891e-02,  8.3936e+01,  9.3867e+01,  8.9561e+01,  8.9824e+01,
         6.8788e-01]), array([ 0.00027943, -0.15736136,  0.07855908]))


In [ ]:
current_angles, current_tcp = robot.get_observation()
for _ in range(10):
    for k in np.arange(-0.05, 0.05, 0.01):
        current_tcp[0] = k
        current_tcp[1] = -0.16
        current_tcp[2] = 0.05
        current_time = time.time()
        target_angles = robot.kinematics.ik(current_tcp, current_angles, real_robot=True)
        print("time to calculate ik: ", time.time() - current_time)
        alpha = np.arange(0, 1, 0.01)
        for a in alpha:
            interpolated_angles = (1-a)*current_angles + a*target_angles
            robot.send_action(torch.tensor(interpolated_angles))
        current_time = time.time()
        current_angles, current_tcp = robot.get_observation()
        print("time to get observation: ", time.time() - current_time)

    for p in np.arange(0.05, 0.15, 0.01):
        current_tcp[0] = 0.05
        current_tcp[1] = -0.16
        current_tcp[2] = p
        current_time = time.time()
        target_angles = robot.kinematics.ik(current_tcp, current_angles, real_robot=True)
        print("time to calculate ik: ", time.time() - current_time)
        alpha = np.arange(0, 1, 0.01)
        for a in alpha:
            interpolated_angles = (1-a)*current_angles + a*target_angles
            robot.send_action(torch.tensor(interpolated_angles))
        current_time = time.time()
        current_angles, current_tcp = robot.get_observation()
        print("time to get observation: ", time.time() - current_time)

    for k in np.arange(0.05, -0.05, -0.01):
        current_tcp[0] = k
        current_tcp[1] = -0.16
        current_tcp[2] = 0.15
        current_time = time.time()
        target_angles = robot.kinematics.ik(current_tcp, current_angles, real_robot=True)
        print("time to calculate ik: ", time.time() - current_time)
        alpha = np.arange(0, 1, 0.01)
        for a in alpha:
            interpolated_angles = (1-a)*current_angles + a*target_angles
            robot.send_action(torch.tensor(interpolated_angles))
        current_time = time.time()
        current_angles, current_tcp = robot.get_observation()
        print("time to get observation: ", time.time() - current_time)

    for p in np.arange(0.15, 0.05, -0.01):
        current_tcp[0] = -0.05
        current_tcp[1] = -0.16
        current_tcp[2] = p
        current_time = time.time()
        target_angles = robot.kinematics.ik(current_tcp, current_angles, real_robot=True)
        print("time to calculate ik: ", time.time() - current_time)
        alpha = np.arange(0, 1, 0.01)
        for a in alpha:
            interpolated_angles = (1-a)*current_angles + a*target_angles
            robot.send_action(torch.tensor(interpolated_angles))
        current_time = time.time()
        current_angles, current_tcp = robot.get_observation()
        print("time to get observation: ", time.time() - current_time)

        

In [3]:
robot.grasp(False)

INFO:so100_robot_control.robot_interface:Joint angles: tensor([ 0.2637, 84.7266, 90.7031, 89.5605, 90.2637,  0.8598])
INFO:so100_robot_control.robot_interface:TCP: [-0.00087756 -0.16589124  0.08716617]
/Users/denizbekleyisseven/workspace/SO100_Control/so100_robot_control/robot_interface.py:155: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.send_action(torch.tensor(current_angles))


In [ ]:
a = np.array([0.05, -0.05, 0.08])
b = np.array([-0.1, -0.05, -0.0])
robot.move_tcp(a)
robot.move_tcp(b)
robot.move_tcp(a)

In [ ]:
robot.get_observation()

In [ ]:
robot.move_tcp_to(np.array([ 0.0, -0.35,  0.15]))

In [ ]:

robot.move_tcp(np.array([0,0,-0.05]))

In [ ]:
# 2) Oscillation parameters
amplitude = 0.03    # meters peak‐to‐zero (so ±5 cm)
frequency = 0.1     # Hz (one full up‐and‐down every 10 s)
dt = 0.02           # control loop period (s) → 50 Hz


In [ ]:
start_t = time.time()
while True:
    t = time.time() - start_t
    # z(t)=A·sin(2πft), so v_z = A·2πf·cos(2πft)
    vz = amplitude * 2 * np.pi * frequency * np.cos(2 * np.pi * frequency * t)
    cart_vel = np.array([0.0, 0.0, vz])

    # move_tcp expects a position delta; vel * dt gives the step size
    robot.move_tcp(cart_vel * dt)
    time.sleep(dt)

In [7]:
freq = 30
dt = 1.0 / freq
time_to_execute = 1
cart_vel = np.array([0.0, 0.0, 0.0])
for i in range(time_to_execute * freq):
    robot.move_tcp(cart_vel * dt)
    time.sleep(dt)

INFO:so100_robot_control.robot_interface:Joint angles: tensor([-0.4395, 85.0781, 92.6367, 89.5605, 89.6484,  0.6879])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00142714 -0.1612661   0.08408809]
INFO:so100_robot_control.robot_interface:Joint angles: tensor([-0.4395, 85.0781, 92.6367, 89.5605, 89.6484,  0.6879])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00142714 -0.1612661   0.08408809]
INFO:so100_robot_control.robot_interface:Joint angles: tensor([-0.4395, 84.2871, 93.3398, 89.5605, 89.6484,  0.6879])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00140949 -0.15896559  0.08053373]
INFO:so100_robot_control.robot_interface:Joint angles: tensor([-0.4395, 83.6719, 93.4277, 89.5605, 89.6484,  0.6879])
INFO:so100_robot_control.robot_interface:TCP: [ 0.0014045  -0.15831519  0.07871884]
INFO:so100_robot_control.robot_interface:Joint angles: tensor([-0.3516, 83.3203, 93.7793, 89.5605, 89.6484,  0.6879])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00111642 -0.15714608  0.

In [35]:
robot.send_action(home)
time.sleep(1)
robot.move_tcp_to(np.array([-0.17,-0.15,0.13]))
robot.grasp(False)

INFO:so100_robot_control.robot_interface:Joint angles: tensor([ 0.4395, 85.0781, 90.4395, 89.5605, 89.8242,  0.6019])
INFO:so100_robot_control.robot_interface:TCP: [-0.00146901 -0.16672568  0.08871536]


time to calculate ik:  0.14197206497192383


INFO:so100_robot_control.robot_interface:Joint angles: tensor([39.3750, 83.8477, 83.7598, 78.9258, 90.2637,  0.6879])
INFO:so100_robot_control.robot_interface:TCP: [-0.14664713 -0.15389037  0.10274489]
INFO:so100_robot_control.robot_interface:Joint angles: tensor([40.9570, 83.8477, 83.5840, 78.5742, 90.2637,  0.6879])
INFO:so100_robot_control.robot_interface:TCP: [-0.15230034 -0.15066741  0.1034014 ]


time to get observation:  0.038385868072509766


In [23]:
robot.move_tcp(np.array([0.0,-0.0,-0.02]))

INFO:so100_robot_control.robot_interface:Joint angles: tensor([38.6719, 84.8145, 73.3008, 70.1367, 90.2637, 39.5529])
INFO:so100_robot_control.robot_interface:TCP: [-0.16815456 -0.18530296  0.14696397]


time to calculate ik:  0.08432579040527344


INFO:so100_robot_control.robot_interface:Joint angles: tensor([38.6719, 80.1562, 74.9707, 70.1367, 90.2637, 39.5529])
INFO:so100_robot_control.robot_interface:TCP: [-0.16725247 -0.18417574  0.12191458]


time to get observation:  0.0413968563079834


In [16]:
robot.send_action(home)

In [19]:
robot.move_tcp(np.array([0.0,-0.0,0.12]))

INFO:so100_robot_control.robot_interface:Joint angles: tensor([38.6719, 87.5391, 75.3223, 74.8828, 90.2637, 39.5529])
INFO:so100_robot_control.robot_interface:TCP: [-0.15950713 -0.17449833  0.14565306]
/Users/denizbekleyisseven/workspace/SO100_Control/so100_robot_control/robot_interface.py:63: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.send_action(torch.tensor(interpolated_angles))


time to calculate ik:  0.10897207260131836


INFO:so100_robot_control.robot_interface:Joint angles: tensor([38.6719, 94.3066, 66.4453, 68.6426, 90.2637, 39.5529])
INFO:so100_robot_control.robot_interface:TCP: [-0.1672652  -0.18419198  0.21405719]


time to get observation:  0.039711952209472656


In [25]:
# ←——— TUNE THESE ———→
CONTROL_FREQ = 30.0      # control loop rate in Hz
IK_FREQ      = 10.0      # IK solve rate in Hz

DT        = 1.0 / CONTROL_FREQ   # seconds per control tick
IK_PERIOD = 1.0 / IK_FREQ        # seconds between IK solves
# ←—————————————————→

t0 = time.time()
def dummy_joystick():
    """
    Replace this stub with your real read_joystick() that returns
    np.array([dx, dy, dz]) in meters per second.
    Here we do a little up/down sine for demo.
    """
    t = time.time() - t0
    vz = 0.01 * np.sin(2*np.pi*0.5*t)
    return np.array([0.0, -vz, -vz])

robot.dynamic_tcp_control(
    read_joystick_fn=dummy_joystick,
    dt=DT,
    ik_period=IK_PERIOD
)


INFO:so100_robot_control.robot_interface:Joint angles: tensor([41.0449, 90.7031, 76.9043, 79.2773, 90.2637, 39.8108])
INFO:so100_robot_control.robot_interface:TCP: [-0.1590565  -0.15788458  0.14803472]


Dynamic control stopped.


In [42]:
robot.get_observation()

INFO:so100_robot_control.robot_interface:Joint angles: tensor([-0.4395, 85.1660, 90.0879, 89.7363, 89.7363,  0.6019])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00147281 -0.16722065  0.08975577]


(tensor([-0.4395, 85.1660, 90.0879, 89.7363, 89.7363,  0.6019]),
 array([ 0.00147281, -0.16722065,  0.08975577]))

In [16]:
robot.move_tcp_to(np.array([-0.16,-0.15,0.15]))

INFO:so100_robot_control.robot_interface:Joint angles: tensor([41.4844, 72.4219, 65.2148, 94.2188, 90.0879, 39.6389])
INFO:so100_robot_control.robot_interface:TCP: [-0.15328959 -0.14855795  0.10702064]
/Users/denizbekleyisseven/workspace/SO100_Control/so100_robot_control/robot_interface.py:83: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.send_action(torch.tensor(interpolated_angles))


time to calculate ik:  0.09311318397521973


INFO:so100_robot_control.robot_interface:Joint angles: tensor([41.6602, 74.0039, 64.7754, 94.3066, 90.0879, 39.5529])
INFO:so100_robot_control.robot_interface:TCP: [-0.1543968  -0.14873434  0.11365243]


time to get observation:  0.03550004959106445


In [15]:
robot.grasp(False)

INFO:so100_robot_control.robot_interface:Joint angles: tensor([41.5723, 74.5312, 64.5117, 94.3945, 90.1758,  9.1144])
INFO:so100_robot_control.robot_interface:TCP: [-0.15434072 -0.14920809  0.11615571]
/Users/denizbekleyisseven/workspace/SO100_Control/so100_robot_control/robot_interface.py:154: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.send_action(torch.tensor(current_angles))


In [3]:
# move to first piece
robot.move_tcp_to(np.array([0.13,-0.16,0.1]))
# grasp false
robot.grasp(False)
#sleep
time.sleep(1)
# move tcp down  in z   
robot.move_tcp(np.array([0.0,0.0,-0.05]))
# grasp true
robot.grasp(True)
#sleep
time.sleep(1)
# move robot to box 
robot.move_tcp_to(np.array([-0.18,-0.12,0.15]))
#sleep
time.sleep(1)
# grasp true
robot.grasp(False)


INFO:so100_robot_control.robot_interface:Joint angles: tensor([-8.7891e-02,  8.4639e+01,  9.3604e+01,  8.9561e+01,  8.9824e+01,
         6.8788e-01])
INFO:so100_robot_control.robot_interface:TCP: [ 0.00028122 -0.15852628  0.08094659]


IndexError: index 5 is out of bounds for axis 0 with size 5

In [26]:
robot.send_action(home)